= Cookbook for OpenNMS PJSM-2.0 branch
This Chef cookbook installs OpenNMS from the public available package repositories.
The installation is customized for a special feature branch called pjsm-2.0 which aims for special features regarding event forwarding to a central OpenNMS instance.

= Requirements and environments
The cookbook is build based on the following requirements:

 * Internet access to download and run a provided CentOS 6.5 base image
 * Vagrant 1.6.3+
 * VirtualBox 4.3.14
 * Virtual
 * CentOS 6.5
 * Oracle Java 1.7

== Contributing

1. Fork the repository on Github
2. Create a named feature branch (i.e. `add-new-recipe`)
3. Write your change
4. Write tests for your change (if applicable)
5. Run the tests, ensuring they all pass
6. Submit a Pull Request

== License and Authors

Author:: Ronny Trommer <ronny@opennms.org>
Copyright (c) 2014 The OpenNMS Group, Inc.
License:: Apache License, Version 2.0

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
